.TH CATTIE "1" "October 2023" "cattie 1.0" "User Commands"

.SH NAME
cattie \- manual page for cattie 1.0

.SH SYNOPSIS
Usage cattie [options] <arguments>

.SH OPTIONS
.HP
\fB\-\-help\fR, \fB\-h\fR
.IP
Show this message and exit
.HP
\fB\-\-version\fR, \fB\-v\fR
.IP
Show the version and exit
.HP
\fB\-\-trace=\fR<file>, \fB\-t\fR <file>
.IP
<file> is the path of the debug file
.HP
\fB\-\-debug\-level=\fR<number>, \fB\-d\fR <number>
.IP
<number> is the level of debug level
.PP

.SH DESCRIPTION
.PP
cattie logic game

.SH BUGS
For reporting bugs, send a email to:

<repiazza@gmail.com>

<gustavo.bacagine@protonmail.com>

.SH AUTHOR
Renato Fermi <repiazza@gmail.com>

Gustavo Bacagine <gustavo.bacagine@protonmail.com>

